package parser;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int _bool = 23;
  public static final int _if = 27;
  public static final int _while = 30;
  public static final int _int = 22;
  public static final int lv = 4;
  public static final int main = 20;
  public static final int lesse = 13;
  public static final int rv = 5;
  public static final int or = 7;
  public static final int lp = 2;
  public static final int _else = 29;
  public static final int output = 26;
  public static final int rp = 3;
  public static final int input = 25;
  public static final int _char = 24;
  public static final int dotcomma = 18;
  public static final int _float = 21;
  public static final int div = 10;
  public static final int EOF = 0;
  public static final int id = 32;
  public static final int less = 12;
  public static final int min = 11;
  public static final int _const = 33;
  public static final int assign = 19;
  public static final int error = 1;
  public static final int plus = 8;
  public static final int neq = 17;
  public static final int mul = 9;
  public static final int _for = 31;
  public static final int _elseif = 28;
  public static final int great = 14;
  public static final int eq = 16;
  public static final int greate = 15;
  public static final int and = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "lp",
  "rp",
  "lv",
  "rv",
  "and",
  "or",
  "plus",
  "mul",
  "div",
  "min",
  "less",
  "lesse",
  "great",
  "greate",
  "eq",
  "neq",
  "dotcomma",
  "assign",
  "main",
  "_float",
  "_int",
  "_bool",
  "_char",
  "input",
  "output",
  "_if",
  "_elseif",
  "_else",
  "_while",
  "_for",
  "id",
  "_const"
  };
}

